### ISSUE TITLE
ffmap backend nicht als root ausführen

### ISSUE THREAD

**Issue by ruebezahl** [freifunkMUC/puppet-ffm#12]
das backend script bitte nicht als root ausführen. es werden random inputdaten aus alfred verarbeitet!
optimalerweise mit einem unpriviligierten user, der auch nirgends raustelefonieren kann. am besten die uid in iptables sperren oder so.

**Comment by ruebezahl** [comment]
ist atm auf testgw3 prototypisch gefixed: läuft als user ffmap mit batctl-queries via sudo

**Comment by spoonicorn** [comment]
sudo + eigener user ist implementiert, lockdown vom user per iptables nicht
