### ISSUE TITLE
ffmac backend generiert die nodes.json ins falsche verzeichnis

### ISSUE THREAD

**Issue by ruebezahl** [freifunkMUC/puppet-ffm#13]
ffmac backend (mkmap.sh) generiert die nodes.json ins falsche verzeichnis:

akutell: DEST=/var/www/$domain

muesste nach: DEST=/var/www/ffmap-frontend-vhost/build/

also: der nginx-vhost fuer die map hat ein rootdir ungleich zu dem aktuell im ffmap-backend mkmap.sh generierten output-pfad.

**Comment by spoonicorn** [comment]
nein, das passt schon alles. Dass frontend + backend auf einem host laufen ist reiner zufall und eigentlich nicht geplant gewesen. (Später soll das Frontend auf einer community-vm laufen)

Das frontend holt sich per wget alle 5 minuten die nodes.json von einer URL (die in diesem fall zufällig vom selben server geservt wird). Der plan ist später sogar mehrere URL zu supporten u. einen compare zu machen zwischen den Verschiedenen versionen. Da müssen wir uns noch überlegen was für ein algorithmus sinn macht um die "gute" nodes.json zu finden (eigentlich sollten alle gleich sein).

**Comment by spoonicorn** [comment]
Ich habe gesehen ihr habt das manuell geändert, aber den cronjob nicht auskommentiert der den wget ausführt. Lasst uns nochmal besprechen wie das am ende laufen soll. Wenn jedes gateway seine nodes.json exportiert u. die map sich das davon holt kann das frontend halt überall laufen egal wo (sogar lokal wer das will).

crontab -u www-data -l
# HEADER: This file was autogenerated at 2015-03-08 17:53:00 +0100 by puppet.
# HEADER: While it can still be managed manually, it is definitely not recommended.
# HEADER: Note particularly that the comments starting with 'Puppet Name' should
# HEADER: not be deleted, as doing so could cause duplicate cron jobs.
# Puppet Name: ffmap: retrieve nodes.json
*/5 * * * * wget -q http://gwtest3.ffmuc.net/nodes.json -O /var/www/testmap.ffmuc.net/build/nodes.json

**Comment by ruebezahl** [comment]
öhm... wenn das so funktioniert hätte, hätte ich es nicht so repariert vorhin. da ist definitv noch was kaputt. die nodes.json wurde auch mit cronjob nie aktualisiert.

**Comment by spoonicorn** [comment]
das hab ich vorhin grad gefixt, hat ein pfad im PATH gefehlt, nämlich der /usr/local/bin . Blöd zu finden, weil nur das alfred-json drin liegt u. wenn mans mit sudo oder su ausführt er das environment nimmt, der cron aber wohl standardmäßig /usr/local/bin nicht drin hat.

Also jetzt sollte es gehen. Also zum einen die local variante die ihr gebaut habt, die jetzt grade aktiv ist, oder auch die wo's per nginx geservt wird. Welche wir nehmen müssen wir uns noch überlegen. Wenns auf dem gleichen Server läuft macht local schon Sinn, da man so öfter reloaden kann bzw. weniger overhead beim reload hat. ich bau das modul dann so, dass man beides einstellen kann.
