### ISSUE TITLE
freifunkMuc - Repos für ffmap-frontend verwenden

### ISSUE THREAD

**Issue by ruebezahl** [freifunkMUC/puppet-ffm#14]
derzeit sind in site/profile/manifests/community/ffmapfrontend.pp nicht unsere git-repos drin, was dazu führt, das alle möglichen features die wir im Testnetz bereits produktiv haben, fehlen.

**Comment by spoonicorn** [comment]
link auf die richtigen? (+ zu nutzenden branch)

Ansonsten das ist ein hiera parameter, also man kann das default repo per hiera überschreiben

**Comment by spoonicorn** [comment]
https://github.com/freifunkMUC/ffmap

das hier? da gibts eh nur einen Master branch, also diesen nehm ich an.

Muss man was beachten im vergleich zum normalen ffmap-d3. bzw. was ist die nodes_load.json?

**Comment by ruebezahl** [comment]
ich hab das mal auf http://testmap.ffmuc.net einfach per hand druebergebuegelt. muss man also nix beachten, einfach clonen und make ausfuehren.

**Comment by spoonicorn** [comment]
ok, habt ihr sonst noch was verändert? bzw. gings nur um ffmap warum man kein puppet laufen lassen sollte? save mal sicherheitshalber weg was du gemacht hast u. dann würde ich die woche das fertig machen. Also "unser" ffmap + nodes.json cron gefixt (siehe anderes ticket).

**Comment by ruebezahl** [comment]
Ich habe wegen #12 noch einige anpassungen gemacht.

**Comment by spoonicorn** [comment]
vor ein paar tagen im ffmap-backend gefixt (sudo geadded). hab mich von deinem script inspirieren lassen, es dann aber direkt in ffmap eingebaut.

https://github.com/freifunkMUC/ffmap-backend/commit/42cadeeea22a349f8935fb1a67cfab2f8ff8a826

puppet wurde damals auch gefixt, sodass entsprechend in sudoers.d ein file geworfen wird
